# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tsuki-shining #modified by etamsylate on 2022/5/24
subtitle: ''
description: 'Carpe Diem and Do what I like'
keywords: 
author: etamsylate
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.redamancy.tech  #https://etamsylate-pupu.github.io/  #modified by etamsylate on 2022/5/25
#permalink: :year/:month/:day/:title/ #modified by etamsylate on 2022/11/18
root: /
permalink: :category/:urlname.html
permalink_defaults:
  urlname: index
pretty_urls:
 trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
 trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false #true originally, modified by etamsylayte on 2022/5/26
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: material  #modified by etamsylate 2022/5/24

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
- type: git
  #repository: https://github.com/etamsylate-pupu/etamsylate-pupu.github.io.git
  repository: 
    github: git@github.com:etamsylate-pupu/etamsylate-pupu.github.io.git,main
    coding: git@e.coding.net:redamancy7/hexoblog/hexoBlog.git,master
  #branch: main
  # type: ''
- type: baidu_url_submitter


#add hexo-generator-search plugin
search:
  path: search.xml
  field: post

# #add SEO Optimization
Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

baidusitemap:
  path: baidusitemap.xml
sitemap:
  path: sitemap.xml

#设置百度主动推送
baidu_url_submit:
  count: 5
  host:  blog.redamancy.tech #www.etamsylate-pupu.github.io
  token: 0P15CxDaYHhTpFKc #0P15CxDaYHhTpFKc #codeva-V3X1937QFp
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里，这个默认

#代码高亮
prism_plugin:
  enable: false
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow' #tomorrow
  line_number: false   # default false
  custom_css:

#文章字数统计
wordCount:
  enable: true
  postWordCount: true
  min2read: true
  totalCount: true


